title: 冼国基
description: 我的个人博客
author: 冼国基
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/xianguoji
about: Freelance developer

baseurl: "https://codeasashu.github.io/hcz-jekyll-blog/about/"
url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
