title: 冼国基的博客
email: 375751459@qq.com
author:
  picture: ./images/myphoto.jpg #URL FORMAT
  name: 冼国基
  location: Rio de Janeiro - Brazil
  description: "菜鸟前端工程师"
description: only my simple vision of casper theme
baseurl: "/"
url: https://hugocarreira.github.io/jekyll-vision-casper-theme
twitter_username: hugocolombo23
github_username:  hugocarreira
github_url: https://hugocarreira.github.io/jekyll-vision-casper-theme/

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
